#!/bin/bash

basedir=$(dirname "$0")
cmdfile="$basedir/.tmp/csvtmp"
mkdir -p "$basedir/.tmp"
: > "$cmdfile"

while read -r data; do
  echo $data >> $cmdfile
done;

out=$(goexec "utils" "csv" "$cmdfile" "$@")
echo "$out"

: > "$cmdfile"